package com.mobileheal.app.di

import com.mobileheal.app.BuildConfig
import com.mobileheal.app.generated.RulesDefaults
import com.mobileheal.app.platform.HealAlerts
import com.mobileheal.app.platform.HealNotifier
import com.mobileheal.data.remote.BaseUrl
import com.mobileheal.data.remote.ClientHeaders
import java.net.URLEncoder
import com.mobileheal.domain.model.AppRules
import com.mobileheal.domain.model.FieldRule
import com.mobileheal.domain.repository.LiveUpdatesRepository
import com.mobileheal.domain.repository.ProfileRepository
import com.mobileheal.domain.usecase.LoadProfileUseCase
import com.mobileheal.domain.usecase.ObserveLiveUpdatesUseCase
import com.mobileheal.domain.usecase.ResolveNavigationUseCase
import com.mobileheal.domain.usecase.SaveProfileUseCase
import com.mobileheal.domain.usecase.ValidateProfileUseCase
import dagger.Binds
import dagger.Module
import dagger.Provides
import dagger.hilt.InstallIn
import dagger.hilt.components.SingletonComponent
import javax.inject.Qualifier

@Qualifier
@Retention(AnnotationRetention.BINARY)
annotation class ProfileId

@Module
@InstallIn(SingletonComponent::class)
abstract class AppModule {
    @Binds abstract fun healAlerts(impl: HealNotifier): HealAlerts

    companion object {
        @Provides @BaseUrl fun baseUrl(): String = BuildConfig.BASE_URL
        @Provides @ProfileId fun profileId(): Int = BuildConfig.PROFILE_ID

        /** Identifies this build to the server, so the portal can show which app (and source folder) is connected. */
        @Provides @ClientHeaders fun clientHeaders(): Map<String, String> = mapOf(
            "X-MobileHeal-App" to "${BuildConfig.APPLICATION_ID} ${BuildConfig.VERSION_NAME}",
            "X-MobileHeal-Rules" to RulesDefaults.SPEC_VERSION,
            "X-MobileHeal-Workspace" to URLEncoder.encode(BuildConfig.SOURCE_FOLDER, "UTF-8"),
        )

        /** Build-time rules generated by the MobileHeal workflow; replaced live by CONFIG_UPDATED. */
        @Provides fun initialRules(): AppRules = AppRules(
            fields = RulesDefaults.REQUIRED_FIELDS.map { FieldRule(it, required = true) } +
                RulesDefaults.OPTIONAL_FIELDS.map { FieldRule(it, required = false) },
            ui = RulesDefaults.UI,
        )
    }
}

/** Use cases are pure Kotlin (no @Inject in :domain), so they are provided here. */
@Module
@InstallIn(SingletonComponent::class)
object DomainModule {
    @Provides fun validateProfile() = ValidateProfileUseCase()
    @Provides fun resolveNavigation() = ResolveNavigationUseCase()
    @Provides fun loadProfile(repository: ProfileRepository) = LoadProfileUseCase(repository)
    @Provides fun saveProfile(repository: ProfileRepository) = SaveProfileUseCase(repository)
    @Provides fun observeLiveUpdates(repository: LiveUpdatesRepository) = ObserveLiveUpdatesUseCase(repository)
}
