"""Regression test for INC-5: AttributeError in make_greeting (greeting.py:5).

Generated by the MobileHeal healer from the input captured in production.
"""
from app.features.greeting import make_greeting

CAPTURED_INPUT = {   'profile': {   'email': 'demo-45540@example.com',
                   'id': 2,
                   'name': None,
                   'phone_number': None,
                   'updated_at': '2026-10-08 05:37:25'}}


def test_inc_5_does_not_crash():
    # Previously raised AttributeError: 'NoneType' object has no attribute 'split'
    make_greeting(**CAPTURED_INPUT)
