"""Regression test for INC-22: [DEV] KeyError in contact_card (contact.py:5).

Generated by the MobileHeal healer from the input captured in production.
"""
from app.features.contact import contact_card

CAPTURED_INPUT = {   'profile': {   'email': 'sam-75715@example.com',
                   'id': 4,
                   'name': 'Sam Rivera',
                   'phone_number': None,
                   'updated_at': '2026-10-08 23:27:55'}}


def test_inc_22_does_not_crash():
    # Previously raised KeyError: 'city'
    contact_card(**CAPTURED_INPUT)
