"""GENERATED contract tests for CR-43 — regenerated by the MobileHeal workflow.

They pin the rules in backend/requirements.txt so an accidental edit fails CI.
"""
import os
from pathlib import Path

from app.rules import missing_fields, parse_spec

SPEC = Path(os.getenv("MOBILEHEAL_SPEC") or Path(__file__).resolve().parents[1] / "requirements.txt")
EXPECTED_REQUIRED = ["name", "email", "restaurant_name", "menu_item", "quantity", "fulfillment_method"]
EXPECTED_OPTIONAL = ["table_number", "special_instructions", "contact_phone"]
EXPECTED_UI = {
    "after_save": "success_screen",
    "app_title": "Restaurant Ordering (Demo)",
    "background_color": "#FFFFFF",
    "banner_color": "#212121",
    "banner_message": "Demo login: test / test",
    "banner_text_color": "#FFFFFF",
    "button_color": "#079455",
    "button_label": "Place order",
    "button_text_color": "#FFFFFF",
    "success_message": "Your order has been submitted successfully (demo flow).",
    "success_title": "Order placed"
}


def _spec():
    return parse_spec(SPEC.read_text(encoding="utf-8"))


def test_spec_parses_with_expected_rules():
    s = _spec()
    assert [r.field for r in s.rules if r.required] == EXPECTED_REQUIRED
    assert [r.field for r in s.rules if not r.required] == EXPECTED_OPTIONAL


def test_ui_rules_match():
    assert _spec().ui == EXPECTED_UI


def test_blank_profile_is_flagged_for_every_required_field():
    assert missing_fields(_spec().rules, {}) == EXPECTED_REQUIRED


def test_complete_profile_is_healthy():
    full = {f: "x" for f in EXPECTED_REQUIRED}
    assert missing_fields(_spec().rules, full) == []
