"""SnipBook — backend generated by the MobileHeal Backend Engineer agent.

Run standalone:  uvicorn prototypes.snipbook.server:app --reload
(MobileHeal also serves it live at /apps/snipbook/api/…)
"""
import re
import sqlite3
import uuid
from datetime import datetime, timezone

from fastapi import FastAPI, HTTPException

MODEL = {
  "customers": [
    {
      "name": "full_name",
      "type": "string",
      "required": true
    },
    {
      "name": "email",
      "type": "email",
      "required": false
    },
    {
      "name": "phone",
      "type": "phone",
      "required": true
    },
    {
      "name": "notes",
      "type": "text",
      "required": false
    },
    {
      "name": "marketing_opt_in",
      "type": "bool",
      "required": false
    }
  ],
  "services": [
    {
      "name": "name",
      "type": "string",
      "required": true
    },
    {
      "name": "description",
      "type": "text",
      "required": false
    },
    {
      "name": "duration_minutes",
      "type": "number",
      "required": true
    },
    {
      "name": "price",
      "type": "money",
      "required": true
    },
    {
      "name": "is_active",
      "type": "bool",
      "required": true
    }
  ],
  "staffs": [
    {
      "name": "first_name",
      "type": "string",
      "required": true
    },
    {
      "name": "last_name",
      "type": "string",
      "required": true
    },
    {
      "name": "email",
      "type": "email",
      "required": false
    },
    {
      "name": "phone",
      "type": "phone",
      "required": false
    },
    {
      "name": "role",
      "type": "enum",
      "required": true,
      "options": [
        "stylist",
        "owner",
        "admin"
      ]
    },
    {
      "name": "is_active",
      "type": "bool",
      "required": true
    }
  ],
  "appointments": [
    {
      "name": "customer_id",
      "type": "string",
      "required": true
    },
    {
      "name": "service_id",
      "type": "string",
      "required": true
    },
    {
      "name": "staff_id",
      "type": "string",
      "required": true
    },
    {
      "name": "start_at",
      "type": "datetime",
      "required": true
    },
    {
      "name": "end_at",
      "type": "datetime",
      "required": true
    },
    {
      "name": "status",
      "type": "enum",
      "required": true,
      "options": [
        "booked",
        "confirmed",
        "completed",
        "canceled",
        "no_show"
      ]
    },
    {
      "name": "total_price",
      "type": "money",
      "required": true
    },
    {
      "name": "notes",
      "type": "text",
      "required": false
    }
  ]
}
app = FastAPI(title="SnipBook API")
db = sqlite3.connect("snipbook.db", check_same_thread=False)
db.execute("CREATE TABLE IF NOT EXISTS records (entity TEXT, id TEXT, data TEXT, PRIMARY KEY (entity, id))")
EMAIL = re.compile(r"^[^@\s]+@[^@\s]+\.[^@\s]+$")


def validate(entity: str, body: dict) -> dict:
    fields = MODEL.get(entity)
    if fields is None:
        raise HTTPException(404, "unknown resource")
    out = {}
    for f in fields:
        v = body.get(f["name"])
        if v in (None, ""):
            if f["required"]:
                raise HTTPException(422, f"{f['name']} is required")
            continue
        if f["type"] in ("number", "money"):
            try:
                v = float(v)
            except (TypeError, ValueError):
                raise HTTPException(422, f"{f['name']} must be a number")
        if f["type"] == "email" and not EMAIL.match(str(v)):
            raise HTTPException(422, f"{f['name']} must be a valid email")
        if f["type"] == "enum" and v not in f["options"]:
            raise HTTPException(422, f"{f['name']} must be one of {f['options']}")
        out[f["name"]] = v if f["type"] != "bool" else bool(v)
    return out
