"""iOS developer agent — turns approved requirements into SwiftUI code for the iOS app.

Template engine (works offline): dedicated after-save screens (SwiftUI view + previews) registered in
GeneratedDestinations.swift. Field, look-and-feel and navigation rules are data-driven at runtime
(AppRules pushed live), and RulesDefaults.swift is regenerated by the workflow on every change.
"""
from __future__ import annotations

import re
from typing import Dict, List

from .rules import parse_spec

IOS_DIR = "ios/MobileHeal"
DESTINATIONS = f"{IOS_DIR}/Generated/GeneratedDestinations.swift"
SCREENS_DIR = f"{IOS_DIR}/Generated/Screens"


def _pascal(s: str) -> str:
    return "".join(w.capitalize() for w in re.split(r"[^A-Za-z0-9]+", s) if w)


def screen_file(sid: str, title: str) -> str:
    P = _pascal(sid)
    t = title.replace("\\", "\\\\").replace('"', '\\"')
    return f'''// GENERATED by the MobileHeal iOS developer agent for screen "{sid}".
import MobileHealKit
import SwiftUI

/// Dedicated destination shown after a successful save (`ui.after_save = {sid}`).
struct {P}Screen: View {{
    let spec: ScreenSpec
    @Environment(\\.dismiss) private var dismiss

    var body: some View {{
        VStack(spacing: 20) {{
            Image(systemName: "hand.wave.fill")
                .font(.system(size: 56))
                .foregroundStyle(.tint)
                .accessibilityHidden(true)
            Text(spec.title)
                .font(.largeTitle.bold())
                .multilineTextAlignment(.center)
            if !spec.message.isEmpty {{
                Text(spec.message)
                    .font(.body)
                    .foregroundStyle(.secondary)
                    .multilineTextAlignment(.center)
            }}
            Button("Continue") {{ dismiss() }}
                .buttonStyle(.borderedProminent)
                .controlSize(.large)
                .accessibilityIdentifier("{sid}.continue")
        }}
        .padding(32)
        .frame(maxWidth: .infinity, maxHeight: .infinity)
        .navigationTitle(spec.title)
        .navigationBarTitleDisplayMode(.inline)
    }}
}}

#Preview("{title}") {{
    NavigationStack {{
        {P}Screen(spec: ScreenSpec(id: "{sid}", title: "{t}", message: "Thanks — your details are up to date."))
    }}
}}

#Preview("Without message") {{
    NavigationStack {{ {P}Screen(spec: ScreenSpec(id: "{sid}", title: "{t}", message: "")) }}
}}
'''


def destinations_file(ids: List[str]) -> str:
    cases = "\n".join(f'        case "{i}":\n            return AnyView({_pascal(i)}Screen(spec: spec))' for i in ids)
    id_list = ", ".join(f'"{i}"' for i in ids)
    return f'''// GENERATED by the MobileHeal iOS developer agent — registry of dedicated after-save screens.
import MobileHealKit
import SwiftUI

enum GeneratedDestinations {{
    static let ids: Set<String> = [{id_list}]

    static func view(for spec: ScreenSpec) -> AnyView? {{
        switch spec.id {{
{cases + chr(10) if cases else ""}        default:
            return nil
        }}
    }}
}}
'''


def lint(files: Dict[str, str]) -> List[dict]:
    out = []
    for path, src in files.items():
        if not path.endswith(".swift"):
            continue
        if "Screens/" in path and "#Preview" not in src:
            out.append({"path": path, "severity": "error", "message": "screen has no #Preview"})
        if re.search(r"[A-Za-z0-9_\)\]]!\.", src):
            out.append({"path": path, "severity": "warn", "message": "force unwrap — prefer optional binding"})
        if src.count("{") != src.count("}"):
            out.append({"path": path, "severity": "error", "message": "unbalanced braces"})
    return out


class IOSAgent:
    def __init__(self, workflow):
        self.wf = workflow
        self.root = workflow.root

    @property
    def present(self) -> bool:
        return (self.root / "ios" / "MobileHeal").is_dir()

    def _existing_ids(self) -> List[str]:
        p = self.root / DESTINATIONS
        if not p.exists():
            return []
        m = re.search(r"ids: Set<String> = \[(.*?)\]", p.read_text(encoding="utf-8"))
        return re.findall(r'"([a-z0-9_]+)"', m.group(1)) if m else []

    def run(self, cr: dict) -> dict:
        result = {"engine": "templates", "files": {}, "plan": None, "lint": []}
        if not self.present:
            result["plan"] = {"summary": "No iOS app in this project.", "changes": [], "notes": []}
            return result
        before, after = parse_spec(cr.get("base_spec") or ""), parse_spec(cr["spec_text"])
        target = after.ui.get("after_save")
        existing = self._existing_ids()
        changes, notes = [], []
        if target and target not in ("stay", "success_screen") and target not in existing:
            title = after.ui.get(f"screen.{target}.title") or " ".join(w.capitalize() for w in target.split("_"))
            P = _pascal(target)
            result["files"][f"{SCREENS_DIR}/{P}Screen.swift"] = screen_file(target, title)
            result["files"][DESTINATIONS] = destinations_file(sorted(set(existing) | {target}))
            changes += [{"path": f"{SCREENS_DIR}/{P}Screen.swift", "action": "create",
                         "purpose": f"{P}Screen: SwiftUI destination with previews"},
                        {"path": DESTINATIONS, "action": "modify", "purpose": f"register screen “{target}”"}]
        if {r.field: r.constraint for r in after.rules} != {r.field: r.constraint for r in before.rules}:
            notes.append("Field rules are rendered and validated generically by ProfileViewModel; RulesDefaults.swift is regenerated.")
        if {k: v for k, v in after.ui.items() if not k.startswith("screen.")} != {k: v for k, v in before.ui.items() if not k.startswith("screen.")}:
            notes.append("Look-and-feel rules are applied live from AppRules.ui — no code change needed.")
        result["plan"] = {"summary": (f"Implement the {after.ui.get(f'screen.{target}.title', target)} screen in SwiftUI"
                                      if changes else "No new Swift code required — this change is data-driven in the iOS app."),
                          "changes": changes, "notes": notes}
        result["lint"] = lint(result["files"])
        return result
