"""PawMart — backend generated by the MobileHeal Backend Engineer agent.

Run standalone:  uvicorn prototypes.pawmart.server:app --reload
(MobileHeal also serves it live at /apps/pawmart/api/…)
"""
import re
import sqlite3
import uuid
from datetime import datetime, timezone

from fastapi import FastAPI, HTTPException

MODEL = {
  "users": [
    {
      "name": "user_id",
      "type": "string",
      "required": true
    },
    {
      "name": "full_name",
      "type": "string",
      "required": true
    },
    {
      "name": "email",
      "type": "email",
      "required": true
    },
    {
      "name": "phone",
      "type": "phone",
      "required": false
    },
    {
      "name": "is_marketing_opt_in",
      "type": "bool",
      "required": false
    }
  ],
  "pets": [
    {
      "name": "pet_id",
      "type": "string",
      "required": true
    },
    {
      "name": "user_id",
      "type": "string",
      "required": true
    },
    {
      "name": "name",
      "type": "string",
      "required": true
    },
    {
      "name": "species",
      "type": "enum",
      "required": true,
      "options": [
        "Dog",
        "Cat",
        "Bird",
        "Fish",
        "SmallAnimal",
        "Reptile",
        "Other"
      ]
    },
    {
      "name": "breed",
      "type": "string",
      "required": false
    },
    {
      "name": "birth_date",
      "type": "date",
      "required": false
    },
    {
      "name": "diet_notes",
      "type": "text",
      "required": false
    }
  ],
  "products": [
    {
      "name": "product_id",
      "type": "string",
      "required": true
    },
    {
      "name": "name",
      "type": "string",
      "required": true
    },
    {
      "name": "category",
      "type": "enum",
      "required": true,
      "options": [
        "Food",
        "Treats",
        "Toys",
        "Health",
        "Grooming",
        "Litter",
        "Accessories",
        "Other"
      ]
    },
    {
      "name": "price",
      "type": "money",
      "required": true
    },
    {
      "name": "brand",
      "type": "string",
      "required": false
    },
    {
      "name": "in_stock",
      "type": "bool",
      "required": true
    },
    {
      "name": "image_url",
      "type": "url",
      "required": false
    },
    {
      "name": "description",
      "type": "text",
      "required": false
    }
  ],
  "orders": [
    {
      "name": "order_id",
      "type": "string",
      "required": true
    },
    {
      "name": "user_id",
      "type": "string",
      "required": false
    },
    {
      "name": "status",
      "type": "enum",
      "required": true,
      "options": [
        "Cart",
        "PendingPayment",
        "Paid",
        "Shipped",
        "Delivered",
        "Canceled"
      ]
    },
    {
      "name": "email",
      "type": "email",
      "required": true
    },
    {
      "name": "shipping_address",
      "type": "text",
      "required": true
    },
    {
      "name": "subtotal_amount",
      "type": "money",
      "required": true
    },
    {
      "name": "shipping_amount",
      "type": "money",
      "required": true
    },
    {
      "name": "tax_amount",
      "type": "money",
      "required": true
    },
    {
      "name": "total_amount",
      "type": "money",
      "required": true
    }
  ],
  "order_items": [
    {
      "name": "order_item_id",
      "type": "string",
      "required": true
    },
    {
      "name": "order_id",
      "type": "string",
      "required": true
    },
    {
      "name": "product_id",
      "type": "string",
      "required": true
    },
    {
      "name": "product_name",
      "type": "string",
      "required": true
    },
    {
      "name": "unit_price",
      "type": "money",
      "required": true
    },
    {
      "name": "quantity",
      "type": "number",
      "required": true
    },
    {
      "name": "line_total",
      "type": "money",
      "required": true
    }
  ]
}
app = FastAPI(title="PawMart API")
db = sqlite3.connect("pawmart.db", check_same_thread=False)
db.execute("CREATE TABLE IF NOT EXISTS records (entity TEXT, id TEXT, data TEXT, PRIMARY KEY (entity, id))")
EMAIL = re.compile(r"^[^@\s]+@[^@\s]+\.[^@\s]+$")


def validate(entity: str, body: dict) -> dict:
    fields = MODEL.get(entity)
    if fields is None:
        raise HTTPException(404, "unknown resource")
    out = {}
    for f in fields:
        v = body.get(f["name"])
        if v in (None, ""):
            if f["required"]:
                raise HTTPException(422, f"{f['name']} is required")
            continue
        if f["type"] in ("number", "money"):
            try:
                v = float(v)
            except (TypeError, ValueError):
                raise HTTPException(422, f"{f['name']} must be a number")
        if f["type"] == "email" and not EMAIL.match(str(v)):
            raise HTTPException(422, f"{f['name']} must be a valid email")
        if f["type"] == "enum" and v not in f["options"]:
            raise HTTPException(422, f"{f['name']} must be one of {f['options']}")
        out[f["name"]] = v if f["type"] != "bool" else bool(v)
    return out
